version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: linedb
      POSTGRES_PASSWORD: zKxr70UH7kQGcPKG
      POSTGRES_DB: line_liff_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: linecrm@vsquareclinic.com
      PGADMIN_DEFAULT_PASSWORD: eSSGdu99Yk4iUsUq
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres-data:
  pgadmin-data: